version: "3.4"

services:
  app_comments:
    container_name: app_comments
    environment:
      NODE_ENV: production
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - VUE_APP_BASE_API_URL=https://mvp-chat.coinmarket.guide
        - VUE_APP_BASE_WS_URL=wss://mvp-chat.coinmarket.guide
    ports:
      - 8000:80
